# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mini' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.4.0'
pod 'HandyJSON', '~> 1.6.1'
pod 'SnapKit', '~> 3.1.2’
pod 'SwiftyJSON'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'FMDB','2.6.2'

  target 'miniTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'miniUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
